apiVersion: v1
kind: Template
labels:
  app: jenkins-agent-debian
  template: jenkins-agent-debian-imagestream
metadata:
  annotations:
    description: Jenkins Agent Debian Image - ImageStream
      see https://github.com/faust64/docker-jenkins-agent-debian
    iconClass: icon-openshift
    openshift.io/display-name: Jenkins Agent Debian
    tags: jenkins-agent-debian
  name: jenkins-agent-debian-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Jenkins Debian Agent image
    name: jenkins-agent-debian
